version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check if licsense is expired"
          shell: powershell.exe
          command: |
            Import-Module -Name 'C:\Users\circleci\project\VSCELicense.psd1'
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
            if((Get-Date).AddDays(-2) -lt $test.ExpirationDate) {
              write-host('The license is still in date')
              Exit 0
            } else {
              Write-Host ('The license is expiring and needs to be updated')
              Write-Host ('Expiry Date:', $test.ExpirationDate)
              Exit 1
            }
