version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check if license is expired"
          shell: powershell.exe
          command: |
            Import-Module -Name 'C:\Users\circleci\project\VSCELicense.psd1'
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
            $test = Get-Get-VSCELicenseExpirationDate -Version 2019
            if((Get-Date).AddDays(-2) -lt $test.ExpirationDate) {
              WriteOutput 'The license is still in date'
              Exit 0
            } else {
              Write-Output 'The license is expiring and needs to be updated'
              Write-Output 'Expiry Date:'
              Write-Output $test.ExpirationDate
              Exit 1
            }
