version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check if license is expired"
          shell: powershell.exe
          command: |
            Install-Module PSSlack -Force
            Add-Type -Assembly System.Drawing

            Import-Module -Name 'C:\Users\circleci\project\VSCELicense.psd1'
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

            $test = Get-VSCELicenseExpirationDate -Version 2019
            $expiryStr = $test.ExpirationDate -replace "`n",", " -replace "`r",", "

            Write-Output 'Expiry Date:', $expiryStr

            if((Get-Date).AddDays(-2) -ge $test.ExpirationDate) {
              Write-Output 'The license is still in date'
              Exit 0
            } else {
              $Fields = [pscustomobject]@{
                ExpiryDate = $expiryStr
                TestURL = $env:CIRCLE_BUILD_URL
              } | New-SlackField -Short
              New-SlackMessageAttachment -Color '#ff0000' `
                             -Title 'The Visual Studio License is about to expire' `
                             -TitleLink "$env:CIRCLE_BUILD_URL" `
                             -Text 'Please update the Windows Image' `
                             -Fields $Fields `
                             -AuthorName 'Visual Studio License Checker' `
                             -Fallback 'Your client is bad' |
                New-SlackMessage -IconEmoji :siren: `
                  -AsUser `
                  -Username 'Visual Studio License Checker' |
                Send-SlackMessage -Uri "$env:SLACK_WEBHOOK_URL"
              Write-Output 'The license is expiring and needs to be updated'
              Exit 1
            }

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "15 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
